<?php
$z[0]=Array("field","",377,396);
$z[0][4]['name']="title";
$z[1]=Array("global","",397,423);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",464,486);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",526,577);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3288,3323);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3851,3873);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n            <li class=\"\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",5961,6171);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",6730,6749);
$z[7][4]['name']="title";
$z[8]=Array("type","[field:typelink /]",6875,6933);
$z[8][4]['typeid']="0";
$z[8][4]['row']="1";
$z[9]=Array("field","",6935,6957);
$z[9][4]['name']="typename";
$z[10]=Array("field","",7014,7071);
$z[10][4]['name']="pubdate";
$z[10][4]['function']="strftime(\"%Y-%m-%d\",@me)";
$z[11]=Array("field","",7314,7332);
$z[11][4]['name']="body";
$z[12]=Array("type","[field:typelink /]",7526,7584);
$z[12][4]['typeid']="0";
$z[12][4]['row']="1";
$z[13]=Array("include","",8920,8955);
$z[13][4]['filename']="foot.htm";

?>