<?php
$z[0]=Array("field","",377,396);
$z[0][4]['name']="title";
$z[1]=Array("global","",397,423);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",464,493);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",533,591);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3403,3438);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3943,3965);
$z[5][4]['name']="typename";
$z[6]=Array("channel","\r\n            <li class=\"\"><a href=\"[field:typeurl/]\">[field:typename/]</a></li>\r\n            ",6027,6237);
$z[6][4]['type']="son";
$z[6][4]['currentstyle']="<li class='current'><a href='~typelink~'>~typename~</a></li>";
$z[7]=Array("field","",6855,6876);
$z[7][4]['name']="content";
$z[8]=Array("include","",7024,7059);
$z[8][4]['filename']="foot.htm";
$z[9]=Array("global","",8230,8251);
$z[9][4]['name']="cfg_jd";
$z[10]=Array("global","",8252,8273);
$z[10][4]['name']="cfg_wd";
$z[11]=Array("global","",9027,9048);
$z[11][4]['name']="cfg_mc";
$z[12]=Array("global","",9059,9080);
$z[12][4]['name']="cfg_dz";
$z[13]=Array("global","",9089,9110);
$z[13][4]['name']="cfg_jd";
$z[14]=Array("global","",9111,9132);
$z[14][4]['name']="cfg_wd";

?>