<?php
$z[0]=Array("field","",375,394);
$z[0][4]['name']="title";
$z[1]=Array("global","",395,421);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",462,491);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",531,589);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("include","",3299,3334);
$z[4][4]['filename']="head.htm";
$z[5]=Array("field","",3839,3861);
$z[5][4]['name']="typename";
$z[6]=Array("list","\r\n                    <li class='col-3-1 not-animated' data-animate='fadeInUp'>\r\n                      <div class=\"product-item\">\r\n                        <div class=\"portfolio-img\"><a href=\"[field:arcurl/]\" target=\"_blank\"><img src=\"[field:litpic/]\" alt=\"[field:title/]\"/></a></div>\r\n                        <div class=\"portfolio-title\">\r\n                          <h2><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h2>\r\n                        </div>\r\n                      </div>\r\n                    </li>\r\n                    ",6294,6890);
$z[6][4]['pagesize']="9";
$z[6][4]['titlelen']="36";
$z[7]=Array("pagelist","",7036,7102);
$z[7][4]['listitem']="index,end,pre,next,pageno";
$z[7][4]['listsize']="5";
$z[8]=Array("include","",7273,7308);
$z[8][4]['filename']="foot.htm";

?>